export interface StoryPage {
  scene?: string;
  mood?: string;
  sounds?: string[];
  /** If this page is the first page of a chapter, the chapter title the
   *  AI assigned to it (e.g. "A Strange Package"). Subsequent pages in
   *  the same chapter leave this undefined/null. The chapter number is
   *  derived from how many earlier pages also have a chapterTitle.
   *  Only populated for Medium/Long AI stories (3 and 5 chapters
   *  respectively). Short/Quick stories flow as one picture-book piece
   *  with no chapter breaks. */
  chapterTitle?: string | null;
  /** Science-of-Reading: vocabulary words flagged by the AI on this
   *  page. 3–5 per page, chosen to be just above the child's comfortable
   *  reading level. Rendered with a subtle underline; tap opens the
   *  definition modal (Word Glow feature). */
  vocabWords?: VocabWord[];
  /** Science-of-Reading: words suitable for Sound-It-Out tap-to-
   *  syllabify and Read-It-Yourself pauses. Includes phonetic syllable
   *  breakdown and difficulty level. Usually overlaps with vocabWords. */
  readAloudWords?: ReadAloudWord[];
}

/** A vocabulary word flagged on a page for the Word Glow tap-to-define
 *  feature. All definitions/fields are pre-generated by Claude at story-
 *  generation time, so the tap is instant (no runtime AI call).
 *
 *  Definitions are age-scaled:
 *   - 2–4 (definition_2_4 is null): modal shows only the big emoji and
 *     speaks the word. Text definitions at that age would be noise.
 *   - 4–7: one sentence, everyday vocabulary.
 *   - 7–10: richer sentence, plus exampleSentence + pronunciation hint.
 */
export interface VocabWord {
  /** Exact word as it appears in the page text (case-preserving). */
  word: string;
  /** One emoji that evokes the word's meaning. Used as the visual
   *  anchor in the modal across all age groups. */
  emoji: string;
  /** Null for the 2–4 band (too young for text definitions). */
  definition_2_4: string | null;
  /** One sentence, 8–14 words, everyday language. */
  definition_4_7: string;
  /** One sentence, 12–20 words, slightly richer; may include metaphor. */
  definition_7_10: string;
  /** A distinct example sentence using the word (not the story's sentence). */
  exampleSentence: string;
  /** Capitalized syllabic pronunciation hint, e.g. "CAN-yun", "eh-KOH". */
  pronunciation: string;
}

/** A word on this page suitable for Sound-It-Out and Read-It-Yourself
 *  mechanics. Phonetic syllables reflect how the word is SPOKEN, not how
 *  it's orthographically hyphenated. */
export interface ReadAloudWord {
  /** Exact word as it appears in the page text. */
  word: string;
  /** Phonetic syllable breakdown. Single-syllable words have a
   *  one-element array. Example: "table" → ["tay", "bul"]. */
  syllables: string[];
  /** 'easy' — CVC words, consonant blends, short vowels.
   *  'intermediate' — long vowels, digraphs, r-controlled.
   *  'hard' — irregular, multi-syllable, schwa patterns. */
  phonicsLevel: "easy" | "intermediate" | "hard";
}

/** An end-of-story (or per-chapter) comprehension question. 3 options
 *  each. Type tells the dashboard which comprehension muscle was
 *  exercised. Connection questions have all options marked correct
 *  because they're about the child's feelings, not facts. */
export interface ComprehensionQuestion {
  type: "recall" | "inference" | "connection";
  question: string;
  options: Array<{
    text: string;
    emoji: string;
    correct: boolean;
  }>;
}

/** A mid-story pause where narration stops and the child picks what
 *  they think happens next. All options are valid — this is an active-
 *  reading primer, not a quiz. */
export interface PredictionPause {
  /** 0-indexed page where the pause fires (after narration finishes). */
  atPageIdx: number;
  question: string;
  options: Array<{
    text: string;
    emoji: string;
  }>;
}

/** Word-level text effect. When the narrator reaches a tagged word, the
 *  word itself transforms inline — the text IS the art, rather than a
 *  flourish floating alongside it. Each effect is a short CSS animation
 *  tied to a `word-fx-*` class in globals.css. */
export type WordEffect =
  /** Word shimmers in warm gold — pairs with "golden", "treasure",
   *  "shining", "glinting". */
  | "glow-gold"
  /** Word sparkles with twinkling dots — pairs with "sparkling",
   *  "magical", "glittering". */
  | "twinkle"
  /** Word scales up and holds briefly — pairs with "big", "huge",
   *  "tall", "giant". */
  | "grow"
  /** Word bounces up and down — pairs with "giggled", "hopped",
   *  "jumped", "bounced". */
  | "bounce"
  /** Word shakes horizontally — pairs with "shivered", "trembled",
   *  "scared". */
  | "shake"
  /** Word pulses in a lub-dub heartbeat rhythm — pairs with "heart
   *  beat" phrases. Pair with `span: 2` so both words pulse in sync.
   *  The pulse plays a few cycles then settles back to baseline. */
  | "heartbeat"
  /** The word stamps onto the page as a big red hand-drawn X. This is
   *  the specific "X marks the spot" effect — use it for the literal
   *  letter X in treasure/map stories. */
  | "red-x"
  /** Word floats upward on a gentle breeze — pairs with "whisper",
   *  "flew", "drifted". */
  | "float"
  /** Word(s) render in a handwritten script font on a paper-cream
   *  background, as if the kid is looking at the physical note / sign
   *  / letter the character is holding. Use `span` to cover the whole
   *  quoted phrase. Structural reveal, same class as red-x. */
  | "handwritten";

/** Diegetic sound effect tied to a word — the actual sound of the thing
 *  the narrator just said. Unlike the old synthesized cues, these play
 *  real .mp3 files from /public/sfx/<name>.mp3. Missing files are silent
 *  no-ops (the scaffold is meant to load real foley samples dropped in
 *  later). */
export type SoundCue =
  | "footsteps"
  | "door-close"
  | "door-creak"
  | "splash"
  | "knock"
  | "wind"
  | "ink-stamp"
  | "giggle"
  | "heart-beat"
  | "whoosh";

/** A moment tied to a specific word in the page narration. When the
 *  highlighted word crosses `at_word`, the visual effect (if any) plays
 *  on the word inline, and the sound cue (if any) fires simultaneously.
 *  Either field is optional — a moment can be visual-only, audio-only,
 *  or both. Gated by the parent-settings effects toggle. */
export interface WordMoment {
  /** Zero-indexed word position in the page's body text (after
   *  splitting on whitespace). */
  at_word: number;
  /** Number of consecutive words to apply the visual effect to,
   *  starting at `at_word`. Defaults to 1. Use 2+ for multi-word
   *  reveals like "heart beat" pulsing together, or for a quoted
   *  phrase rendered as a handwritten note. */
  span?: number;
  /** Optional visual effect applied to the word's span. */
  effect?: WordEffect;
  /** Optional diegetic sound played when the word is reached. */
  sound?: SoundCue;
}

/** A single word's timing within a page's audio, from OpenAI Whisper */
export interface WordTiming {
  word: string;
  start: number;
  end: number;
}

export interface Story {
  id: string;
  title: string;
  emoji: string;
  color: string;
  genre: string;
  age: string;
  pages: [string, string][];
  fullPages?: StoryPage[];
  generated?: boolean;
  /** True for stories in the "Classics" section — retold public domain
   *  tales like Cinderella, The Three Little Pigs, etc. */
  isClassic?: boolean;
  /** Original author/source for classic stories, e.g. "Brothers Grimm",
   *  "Aesop", "Hans Christian Andersen". */
  originalAuthor?: string;
  /** Short one-line description shown in the library for classics. */
  description?: string;
  /** Which child profile this story was saved under. Null = legacy/shared. */
  childProfileId?: string | null;
  duration?: string;
  /** The hero's species/form as selected in the builder — "mermaid",
   *  "dragon", "boy", "girl", "kid", etc. Persisted so that when the
   *  reader progressively regenerates later pages' illustrations, it
   *  can pass heroType to the image model as an extra belt-and-braces
   *  hint on top of the AI-written characterDescription. Optional:
   *  older stories saved before this field existed will be null. */
  heroType?: string;
  characterDescription?: string;
  /** Pre-loaded image URLs (indexed by page number, null = not yet loaded) */
  preloadedImages?: (string | null)[];
  /** Persisted mp3 URLs from Supabase Storage, indexed by page number.
   *  Null entries fall back to on-demand /api/tts generation. */
  audioUrls?: (string | null)[];
  /** Persisted Whisper word timings, indexed by page number. */
  wordTimings?: (WordTiming[] | null)[];
  /** Optional hand-authored word moments, indexed by page number. Each
   *  page has a list of {at_word, effect?, sound?} triples that fire a
   *  word-inline visual effect and/or a diegetic sound when the narration
   *  reaches that word. Pages with no moments can be omitted or null. */
  moments?: (WordMoment[] | null)[];
  /** Science-of-Reading comprehension questions shown after the final
   *  page. Typically 2–3 per story, or 1 per chapter for 7–10 chaptered
   *  stories. Age 2–4 stories should omit these. */
  comprehensionQuestions?: ComprehensionQuestion[];
  /** Science-of-Reading prediction pause (v1.5). One per story. Fires
   *  after narration finishes on the specified page. */
  predictionPause?: PredictionPause;
}

export interface Genre {
  id: string;
  label: string;
  emoji: string;
  color: string;
}

export interface AgeGroup {
  id: string;
  label: string;
}

export interface Duration {
  id: string;
  label: string;
  desc: string;
  minutes: number;
  targetWords: number;
}

export interface Sentence {
  text: string;
  startIdx: number;
  endIdx: number;
}

// AI voice options from OpenAI TTS
export type AIVoiceName = "nova" | "alloy" | "echo" | "fable" | "onyx" | "shimmer";

export interface AIVoiceOption {
  id: AIVoiceName;
  label: string;
  desc: string;
}

export const AI_VOICES: AIVoiceOption[] = [
  { id: "nova", label: "Nova", desc: "Warm & friendly (recommended)" },
  { id: "shimmer", label: "Shimmer", desc: "Gentle & expressive" },
  { id: "fable", label: "Fable", desc: "Storyteller style" },
  { id: "alloy", label: "Alloy", desc: "Balanced & clear" },
  { id: "echo", label: "Echo", desc: "Calm & soothing" },
  { id: "onyx", label: "Onyx", desc: "Deep & resonant" },
];

export type VoiceMode = "ai" | "browser";

export interface SpeechControls {
  speaking: boolean;
  wordIndex: number;
  /**
   * Progress through the currently-highlighted word, 0..1. Updated on
   * every RAF tick while audio plays. Consumers can use it to drive a
   * sub-word "fill sweep" effect (Yoto-style) — a gradient background
   * that advances across the word's letters in real time. At 0 the
   * word has just activated; at 1 the next word is about to activate.
   *
   * When not speaking (or between words), this is 0.
   */
  wordProgress: number;
  words: string[];
  speak: (text: string, onEnd?: () => void) => void;
  stop: () => void;
  /** Pause the currently-playing audio WITHOUT resetting. Safe to call
   *  when nothing is playing (no-op). Companion to resume(). Used by the
   *  Word Glow modal to quiet the narrator while the child reads a
   *  definition; narration picks up mid-word when the modal dismisses. */
  pause: () => void;
  /** Resume playback after pause(). Safe to call when nothing is paused
   *  (no-op) or when stop() has been called (also no-op — doesn't start
   *  anything fresh). */
  resume: () => void;
  prefetch: (text: string, storyId?: string, pageIdx?: number) => void;
  setStoryContext: (storyId?: string, pageIdx?: number) => void;
  // Voice mode
  voiceMode: VoiceMode;
  setVoiceMode: (mode: VoiceMode) => void;
  // AI voice settings
  aiVoice: AIVoiceName;
  setAiVoice: (v: AIVoiceName) => void;
  aiSpeed: number;
  setAiSpeed: (s: number) => void;
  // Browser voice settings (kept for fallback)
  voice: SpeechSynthesisVoice | null;
  setVoice: (v: SpeechSynthesisVoice) => void;
  rate: number;
  setRate: (r: number) => void;
  allVoices: SpeechSynthesisVoice[];
  // Loading state for AI audio
  loading: boolean;
}
